name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run application with Gunicorn
      run: |
        gunicorn --bind 0.0.0.0:5000 main:app &
        sleep 3
        npx localtunnel --port 5000 --subdomain my-floorplan-app
      env:
        FLASK_ENV: production